const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "laptop",
      image: "/iphone.png",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/iphone.pngg",
      span: 2,
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "smart watch",
      image: "/iphone.png",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/iphone.pngg",
      span: 2,
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "power bank",
      image: "/iphone.png",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "A popular shirt",
      span: 2,
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "flash disk",
      image: "/iphone.png",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart looking pants",
      span: 2,
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "sound",
      image: "/iphone.png",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "A popular pants",
      span: 2,
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "laptop",
      image: "/iphone.png",
      price: 75,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "A popular pants",
      span: 2,
    },
  ],
};
export default data;
